Includes context managers for file management in utils
SUSE-Enceladus/cloud-regionsrv-client pull request #109
Opened 2023-01-20 12:44 UTC by apozsuse

I spotted some parts in the utils file that could be improved with the use context managers.

2023-01-20 15:09 UTC, smarlowucf reviewed
I think general python convention is to exit context manager as soon as possible. I.e. once the content is read from file it can be closed. Any processing of that content can happen outside the context manager.

2023-01-20 15:09 UTC, smarlowucf commented on lib/cloudregister/registerutils.py
> +        for entry in credentials:
All the logic doing work on the file data can be outside of the context manager. This allows the file to close right after readlines.

2023-01-20 15:09 UTC, smarlowucf commented on lib/cloudregister/registerutils.py
> +        if (
Ditto

2023-01-20 16:31 UTC, rjschwei commented on lib/cloudregister/registerutils.py
> +        hosts_file.write(entry)
If you are using context manager, I know calling close() is an extra line of code ;), then the creation of the string we write should be outside, i.e.

```
smt_ip = smt_server.get_ipv4()
if has_ipv6_access(smt_server):
    smt_ip = smt_server.get_ipv6()
entry = '%s\t%s\t%s\n' % (
    smt_ip,
    smt_server.get_FQDN(),
    smt_server.get_name()
)
with open('/etc/hosts', 'a') as hosts_file:
    hosts_file.write(smt_hosts_entry_comment)
    hosts_file.write(entry)
```

2023-01-20 16:39 UTC, rjschwei requested changes
See inline comments about scope

2023-01-23 12:12 UTC, jesusbv approved these changes
LGTM

2023-01-23 12:47 UTC, rjschwei approved these changes

2023-01-23 18:00 UTC, smarlowucf approved these changes

2023-01-23 18:49 UTC, merged