Prep for container use
SUSE-Enceladus/cloud-regionsrv-client pull request #122
Opened 2023-05-10 12:26 UTC by rjschwei

This is the start of being able to use cloud-regionsrv-client from a container. Inside a container we do not want systemd and it's dependencies. Change the macro used such that systemd is not automatically set up as package dependency on SLE 15 and later distributions.

2023-05-10 16:11 UTC, jgleissner requested changes
The spec should probably contain `BuildRequires: systemd-rpm-macros`.

2023-05-10 16:11 UTC, jgleissner commented on cloud-regionsrv-client.spec
> +%{?systemd_oredering}
Shouldn't that be `systemd_ordering`?

2023-05-11 06:59 UTC, jgleissner commented
> The spec should probably contain `BuildRequires: systemd-rpm-macros`.

It appears rpm already requires this so I guess adding this wasn't really necessary (sorry), but obviously won't harm.

2023-05-11 11:40 UTC, rjschwei commented
It's always there as was at one point the python-rpm-macros until it was not and then created a bunch of failures. Good to be explicit.

2023-05-11 11:40 UTC, merged