Add tests
SUSE-Enceladus/cloud-regionsrv-client pull request #136
Opened 2023-12-15 14:49 UTC by jesusbv

This is a first step into improving the unit tests, I plan to add more specific/meaningful tests 

This adds 99% coverage, as the SMT ip issue fails, the test is ready but commented 
once uncommented, coverage should be 100%, meaning these tests would have caught
that issue 

```bash
Name                                 Stmts   Miss  Cover   Missing
------------------------------------------------------------------
lib/cloudregister/__init__.py            0      0   100%
lib/cloudregister/amazonec2.py          34      0   100%
lib/cloudregister/googlece.py           23      0   100%
lib/cloudregister/msftazure.py          67      0   100%
lib/cloudregister/registerutils.py     946      0   100%
lib/cloudregister/smt.py               143      4    97%   256-263
------------------------------------------------------------------
TOTAL                                 1213      4    99%

=================================== 210 passed, 5 warnings in 55.35s ====================================
```

2023-12-15 14:50 UTC, jesusbv commented
I will add also the docstrings for the test methods

2023-12-15 16:42 UTC, jgleissner approved these changes
LGTM

2023-12-15 18:00 UTC, smarlowucf approved these changes
Yay tests 🎉

2023-12-15 20:19 UTC, rjschwei requested changes
Didn't get to review all the new tests, ran out of time/steam

2023-12-15 20:19 UTC, rjschwei commented on tests/test_registerutils.py
> +# simulates hosts file containing the ipv6 we are looking for in the test
this says "ipv6" but what follows are ipv4 address, meaning this duplicates the mistake that is already in the tests.

2023-12-18 10:19 UTC, jesusbv commented on lib/cloudregister/registerutils.py
> +        errMsg = 'Could not get product list: %s' % err
Understood, as it was that raised an exception if `subprocess.Popen` produced `OSError`
as cmd was not defined

Will update it to log the command

2023-12-18 10:43 UTC, jesusbv commented on tests/test_smt.py
> +    assert smt.write_cert('/tmp') == '/tmp/registration_server_fc00__1.pem'
Yes, will update
I thought I had changed all the writing to disk tests,
will check I did not miss more of those

2023-12-19 22:13 UTC, rjschwei approved these changes

2023-12-19 22:19 UTC, merged