package build update
SUSE-Enceladus/cloud-regionsrv-client pull request #209
Opened 2024-09-10 21:18 UTC by rjschwei

- The way Python is being built has changed for SUSE distributions. Python 3.6 is, by design no longer available in products SLE Micro and later. We need to use macros that are defined in the build service to pick up the interpreter we want to use for building our code and to find the proper Python module packages we depend on.
- Add a previoulsy forgotten patch for the SLE 12 build that we need to maintain until the EOL of that code stream.

2024-09-10 21:20 UTC, rjschwei commented
Sticking with the Python 3.6 build for SLE 15. When SLE 15 SP3 reaches EOL we can consider switching this to a Python 3.11 build and creating a branch in the build service. Until then I'd rather not have a branch in the build service to maintain a Python 3.6 build for SP1, SP2, and SP3 and a Python 3.11 build for SP4 and later.

2024-09-11 08:24 UTC, schaefi requested changes
Looks good, I tested the package build except for SLE12 due to the missing patch file in the git. Thanks

2024-09-11 08:24 UTC, schaefi commented on cloud-regionsrv-client.spec
> +Patch2:         fix-for-sles12-no-trans_update.patch
The patch file `fix-for-sles12-no-trans_update.patch` is not part of the git repo. Can you please add it like the other patch files. Thanks

2024-09-11 08:24 UTC, schaefi commented on cloud-regionsrv-client.spec
> +Patch2:         fix-for-sles12-no-trans_update.patch
I tested the package build for all maintained targets. One thing I noted is that for SLE15 the package builds against python 3.6, I guess this is intentional ?

2024-09-11 12:22 UTC, schaefi approved these changes
LGTM

2024-09-11 12:22 UTC, merged