Add status registration message
SUSE-Enceladus/cloud-regionsrv-client pull request #69
Opened 2022-03-17 10:54 UTC by jesusbv

- Show registration status in console

This Fixes bsc#1197113

2022-03-17 11:43 UTC, rjschwei requested changes

2022-03-17 11:43 UTC, rjschwei commented on usr/sbin/registercloudguest
> +        print('Registration failed, see /var/log/guestregister for details')
We do not want to print the failure message for every update server we are trying, one summary message, you'll have to set a flag.

2022-03-17 11:43 UTC, rjschwei commented on usr/sbin/registercloudguest
> +                print('Registration failed, see /var/log/guestregister for details')
Ditto, one summary message if registration succeeds or fails.

2022-03-17 12:19 UTC, jesusbv commented on usr/sbin/registercloudguest
> +                print('Registration failed, see /var/log/guestregister for details')
Ack, done.

2022-03-17 14:52 UTC, rjschwei requested changes

2022-03-17 14:52 UTC, rjschwei commented on usr/sbin/registercloudguest
> +    print('Registration failed, see /var/log/guestregister for details')
This is an error and needs to go to stderr, i.e. `file=sys.stderr'

exit code is set later in the code.

2022-03-18 11:28 UTC, rjschwei approved these changes

2022-03-18 11:28 UTC, merged